# GameCache Configuration
# Edit the values below with your information

title = "Emil's boardgames"
bgg_username = EmilStenstrom
<<<<<<< dependabot/pip/scripts/pillow-11.3.0
github_repo = EmilStenstrom/mybgg-EmilStenstrom
=======
github_repo = EmilStenstrom/gamecache-EmilStenstrom
>>>>>>> master
